# NUMPY

In [1]:
import numpy as np
# from numpy import *

In [2]:
L1 = [1,2,3,4,5,6,7,8]# Crear una lista

In [3]:
x1 = np.array(L1 )
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

# dtype:
- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64  'enteros sin signo' 
- float_, float16, float32, float64 (+/-999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b  ∈  float_) 'Numeros complejas'

In [7]:
# MATRIZ DE CEROS
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# MATRIZ DE UNOS
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,12,dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
np.arange(3,5,0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
np.linspace(1., 7., 12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
x.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [34]:
# aplanar el vector con revel
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
np.ravel(x) # aplanar el vector con ravel

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
# una copia del vector colapsado en una dimension
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x # vector original

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
#cambiar filas y columnas
np.transpose(x)


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [38]:
# crear un nuevo array con orden especifico
np.resize(x, (5, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

## PROPIEDADES DE LOS ARRAYS

In [3]:
import numpy as np
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
x.ndim

2

In [6]:
x.shape  # N x M

(3, 4)

In [7]:
x.size # tamaño

12

In [8]:
x.dtype # tipo de dato

dtype('int64')

In [9]:
 x.itemsize # tamaño en bits de cada uno de los elementos de la matrix

8

In [10]:
x.data # ver la posicion de memoria almaceada los datos

In [16]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
x[2] # mostrar fila dos

array([ 8,  9, 10, 11])

In [21]:
x[2,3] # mostrar el elemento de la fila 2 y columna 3

11

In [22]:
# Cambiar el ordenamiento de la matrix
x.shape = (4, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
# extraer sub-matricex
x[2:4, 0:2]

array([[ 6,  7],
       [ 9, 10]])

In [29]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
y[3:8]

array([3, 4, 5, 6, 7])

In [31]:
# segmentos en 2 en 2
y[1:8:2]

array([1, 3, 5, 7])

In [34]:
# traer segmentos de otra matrix con otra matrix
z = np.arange(10, 2, -1)
z
y[z]

array([10,  9,  8,  7,  6,  5,  4,  3])

In [35]:
# acceder por condicion booleana
x = np.arange(50)
x
 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [37]:
cond = (x>24)
cond

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [38]:
x[cond]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
# sustituir un rango de elementos por un valor
x[11:24] = 8
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
# Cambiar valores de la misma longitud
x[0:3] = [3,2,1]
x


array([ 3,  2,  1,  3,  4,  5,  6,  7,  8,  9, 10,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
# numpy solo puede tener un tipo de dato Homogeneo y no puede tener heterogeneida Ej:
x[5] = 3.1416
x


array([ 3,  2,  1,  3,  4,  3,  6,  7,  8,  9, 10,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### COPIAS Y VISTAS DE ARREGLOS

In [43]:
# CREA UNA VARIABLE QUE REFERNCIA A OTRO ARREGLO
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y = x
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
# X tambien cambio por es un referencia 
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
# hacer una copia sin que el original no quede referenciado
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
# Comprobar que no son iguales
z is x

False

In [53]:
y is x

True

In [56]:
# Generar un vista sin que se altere el original
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
s = x[0:2, 1:3]
s

array([[1, 2],
       [6, 7]])

In [60]:
s[:] = 8
s

array([[8, 8],
       [8, 8]])

In [61]:
x

array([[0, 8, 8, 3, 4],
       [5, 8, 8, 8, 9]])

In [62]:
y

array([[0, 8, 8, 3, 4],
       [5, 8, 8, 8, 9]])

In [63]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## FUNCIONES UNIVERSALES
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum 

In [64]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [67]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [68]:
alpha = np.linspace(0,2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [69]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [70]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [75]:
np.tan(alpha)


array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.exp(x) # e^x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [73]:
np.exp2(x) # 2^x

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [77]:
np.power(3,x) # 3^x

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [78]:
np.power(x, 2)


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
np.log(x)

/home/ruber/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [80]:
np.log2(x)

/home/ruber/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [81]:
np.log10(x)

/home/ruber/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [90]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.sum(x)

45

In [83]:
np.nansum(x) # SUMA SIN N/A

45

In [84]:
np.prod(x)

0

In [85]:
np.mean(x) # MEDIA

4.5

In [86]:
np.median(x) # MEDIANA

4.5

In [87]:
# mininimo
np.min(x) 

0

In [89]:
# maximo
np.max(x) 

9

In [91]:
# desviacion tipica
np.std(x)

2.8722813232690143

In [92]:
# varianza
np.var(x)

8.25

In [93]:
# posicion index del valor mas pqueño
np.argmin(x)

0

In [94]:
# posicion del valor mas grande
np.argmax(x)

9

In [95]:
# calcular el persentil 
np.percentile(x, q=0.95)

0.08549999999999999

In [13]:
# Comprobar si hay un booleano true
y = np.array([True, False, True, True])
y

array([ True, False,  True,  True])

In [14]:
# si hay un true
np.any(y)

True

In [16]:
# si todos son true
np.all(y)

False

In [29]:
np.random.seed(2019) # randon con semilla 2019 para que no cambie los valores
z = np.random.random((3,5))
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [30]:
# suma total del arreglo
z.sum()

8.550690063213514

In [31]:
#Suma por Columnas
z.sum(axis=0)

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [32]:
# suma por filas
z.sum(axis=1)

array([3.43890915, 3.19170818, 1.92007274])